[package]
name = "drep"
version = "0.1.0"
authors = ["Zohaib Sibte Hassan <zohaibsh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
structopt = "0.3.15"
notify = "4.0.12"